In [1]:
from sqlalchemy import create_engine,inspect
import pandas as pd
from sqlalchemy import text
import psycopg2 
import numpy as np
import seaborn as sns

In [2]:
engine = create_engine(
    'postgresql+psycopg2://postgres:123456@111.186.56.196:5432/postgres',
    isolation_level="AUTOCOMMIT"
)

In [3]:
# 使用SQLAlchemy的inspect模块获取表和列信息
inspector = inspect(engine)

# 获取所有表的名称
tables = inspector.get_table_names()

# 遍历每个表并获取列名称
for table in tables:
    columns = inspector.get_columns(table)
    column_names = [column['name'] for column in columns]
    print(f"Table '{table}' has columns: {column_names}")

Table 'audio_data' has columns: ['Date', 'file_x', 'ZCR', 'MEANt', 'VARt', 'SKEWt', 'KURTt', 'LEQt', 'BGNt', 'SNRt', 'MED', 'Ht', 'ACTtFraction', 'ACTtCount', 'ACTtMean', 'EVNtFraction', 'EVNtMean', 'EVNtCount', 'MEANf', 'VARf', 'SKEWf', 'KURTf', 'NBPEAKS', 'LEQf', 'ENRf', 'BGNf', 'SNRf', 'Hf', 'EAS', 'ECU', 'ECV', 'EPS', 'EPS_KURT', 'EPS_SKEW', 'ACI', 'NDSI', 'rBA', 'AnthroEnergy', 'BioEnergy', 'BI', 'ROU', 'ADI', 'AEI', 'LFC', 'MFC', 'HFC', 'ACTspFract', 'ACTspCount', 'ACTspMean', 'EVNspFract', 'EVNspMean', 'EVNspCount', 'TFSD', 'H_Havrda', 'H_Renyi', 'H_pairedShannon', 'H_gamma', 'H_GiniSimpson', 'RAOQ', 'AGI', 'ROItotal', 'ROIcover', 'file_name', 'bird_1', 'confidence_1', 'bird_2', 'confidence_2', 'bird_3', 'confidence_3', 'bird_4', 'confidence_4', 'bird_5', 'confidence_5', 'Chords', 'Key', 'Tempo_Estimates', 'Onsets', 'file_y', 'frequencies', 'LTS', 'MEANt_per_bin', 'VARt_per_bin', 'SKEWt_per_bin', 'KURTt_per_bin', 'LEQf_per_bin', 'ENRf_per_bin', 'BGNf_per_bin', 'SNRf_per_bin', 'Ht_per_bin', 'ACI_per_bin', 'ROU_per_bin', 'ACTspFract_per_bin', 'ACTspCount_per_bin', 'EVNspFract_per_bin', 'EVNspMean_per_bin', 'EVNspCount_per_bin', 'AGI_per_bin', 'file', 'isclipped', 'ismusic', 'isspeech', 'class_1', 'confidence_voice_1', 'class_2', 'confidence_voice_2', 'class_3', 'confidence_voice_3', 'class_4', 'confidence_voice_4', 'class_5', 'confidence_voice_5', 'class_6', 'confidence_voice_6', 'class_7', 'confidence_voice_7', 'class_8', 'confidence_voice_8', 'class_9', 'confidence_voice_9', 'class_10', 'confidence_voice_10', 'process', 'place', 'level']
Table 'audioglobal1' has columns: ['file', 'realfilename', 'foldername', 'birdenname', 'birdspgen', 'Date', 'gen', 'sp', 'ssp', 'group', 'en', 'rec', 'cnt', 'loc', 'lat', 'lng', 'alt', 'type', 'sex', 'stage', 'method', 'url', 'file_dataset', 'file-name', 'sono', 'osci', 'lic', 'q', 'length', 'time', 'date', 'uploaded', 'also', 'rmk', 'bird-seen', 'animal-seen', 'playback-used', 'temp', 'regnr', 'auto', 'dvc', 'mic', 'smp', 'fullfilename', 'Date_dataset', 'filewithpath', 'ZCR', 'MEANt', 'VARt', 'SKEWt', 'KURTt', 'LEQt', 'BGNt', 'SNRt', 'MED', 'Ht', 'ACTtFraction', 'ACTtCount', 'ACTtMean', 'EVNtFraction', 'EVNtMean', 'EVNtCount', 'MEANf', 'VARf', 'SKEWf', 'KURTf', 'NBPEAKS', 'LEQf', 'ENRf', 'BGNf', 'SNRf', 'Hf', 'EAS', 'ECU', 'ECV', 'EPS', 'EPS_KURT', 'EPS_SKEW', 'ACI', 'NDSI', 'rBA', 'AnthroEnergy', 'BioEnergy', 'BI', 'ROU', 'ADI', 'AEI', 'LFC', 'MFC', 'HFC', 'ACTspFract', 'ACTspCount', 'ACTspMean', 'EVNspFract', 'EVNspMean', 'EVNspCount', 'TFSD', 'H_Havrda', 'H_Renyi', 'H_pairedShannon', 'H_gamma', 'H_GiniSimpson', 'RAOQ', 'AGI', 'ROItotal', 'ROIcover', 'bird_1', 'confidence_1', 'bird_2', 'confidence_2', 'bird_3', 'confidence_3', 'bird_4', 'confidence_4', 'bird_5', 'confidence_5', 'Key', 'Tempo_Estimates', 'Onsets', 'chordhmm', 'chroma', 'chord', 'chordtime', 'file_name', 'frequencies', 'LTS', 'MEANt_per_bin', 'VARt_per_bin', 'SKEWt_per_bin', 'KURTt_per_bin', 'LEQf_per_bin', 'ENRf_per_bin', 'BGNf_per_bin', 'SNRf_per_bin', 'Ht_per_bin', 'ACI_per_bin', 'ROU_per_bin', 'ACTspFract_per_bin', 'ACTspCount_per_bin', 'EVNspFract_per_bin', 'EVNspMean_per_bin', 'EVNspCount_per_bin', 'AGI_per_bin', 'isclipped', 'ismusic', 'isspeech', 'class_1', 'confidence_voice_1', 'class_2', 'confidence_voice_2', 'class_3', 'confidence_voice_3', 'class_4', 'confidence_voice_4', 'class_5', 'confidence_voice_5', 'class_6', 'confidence_voice_6', 'class_7', 'confidence_voice_7', 'class_8', 'confidence_voice_8', 'class_9', 'confidence_voice_9', 'class_10', 'confidence_voice_10', 'process']
Table 'audio_data2' has columns: ['Date', 'file_x', 'ZCR', 'MEANt', 'VARt', 'SKEWt', 'KURTt', 'LEQt', 'BGNt', 'SNRt', 'MED', 'Ht', 'ACTtFraction', 'ACTtCount', 'ACTtMean', 'EVNtFraction', 'EVNtMean', 'EVNtCount', 'MEANf', 'VARf', 'SKEWf', 'KURTf', 'NBPEAKS', 'LEQf', 'ENRf', 'BGNf', 'SNRf', 'Hf', 'EAS', 'ECU', 'ECV', 'EPS', 'EPS_KURT', 'EPS_SKEW', 'ACI', 'NDSI', 'rBA', 'AnthroEnergy', 'BioEnergy', 'BI', 'ROU', 'ADI', 'AEI', 'LFC', 'MFC', 'HFC', 'ACTspFract', 'ACTspCount', 'ACTspMean', 'EVNspFract', 'EVNspMean', 'EVNspCount', 'TFSD', 'H_Havrda', 'H_Renyi', 'H_pairedShannon', 'H_gamma', 'H_GiniSimpson', 'RAOQ', 'AGI', 'ROItotal', 'ROIcover', 'file_name', 'bird_1', 'confidence_1', 'bird_2', 'confidence_2', 'bird_3', 'confidence_3', 'bird_4', 'confidence_4', 'bird_5', 'confidence_5', 'Key', 'Tempo_Estimates', 'Onsets', 'chordhmm', 'chroma', 'chord', 'chordtime', 'file_y', 'frequencies', 'LTS', 'MEANt_per_bin', 'VARt_per_bin', 'SKEWt_per_bin', 'KURTt_per_bin', 'LEQf_per_bin', 'ENRf_per_bin', 'BGNf_per_bin', 'SNRf_per_bin', 'Ht_per_bin', 'ACI_per_bin', 'ROU_per_bin', 'ACTspFract_per_bin', 'ACTspCount_per_bin', 'EVNspFract_per_bin', 'EVNspMean_per_bin', 'EVNspCount_per_bin', 'AGI_per_bin', 'file', 'isclipped', 'ismusic', 'isspeech', 'class_1', 'confidence_voice_1', 'class_2', 'confidence_voice_2', 'class_3', 'confidence_voice_3', 'class_4', 'confidence_voice_4', 'class_5', 'confidence_voice_5', 'class_6', 'confidence_voice_6', 'class_7', 'confidence_voice_7', 'class_8', 'confidence_voice_8', 'class_9', 'confidence_voice_9', 'class_10', 'confidence_voice_10', 'process', 'place', 'level']

In [7]:
def query_database(columns, table_name, engine):
    # 构建 SQL 查询语句
    column_str = ', '.join([f'"{col}"' for col in columns])  # 处理 SQL 列名
    db_type = engine.dialect.name  # 获取数据库类型
    order_by_clause = "ORDER BY RANDOM()" if db_type in ["sqlite", "postgresql"] else "ORDER BY RAND()"

    query = text(f'SELECT {column_str} FROM {table_name} {order_by_clause} LIMIT 100')

    # 执行查询并加载数据到 DataFrame
    try:
        df = pd.read_sql_query(query, con=engine)
        return df
    except Exception as e:
        print("Error in query execution:", e)
        return None
# 指定查询列
columns = ['file', 'realfilename', 'foldername', 'birdenname', 'birdspgen', 'Date', 'gen', 'sp', 'ssp', 'group', 'en', 'rec', 'cnt', 'loc', 'lat', 'lng', 'alt', 'type', 'sex', 'stage', 'method', 'url', 'file_dataset', 'file-name', 'sono', 'osci', 'lic', 'q', 'length', 'time', 'date', 'uploaded', 'also', 'rmk', 'bird-seen', 'animal-seen', 'playback-used', 'temp', 'regnr', 'auto', 'dvc', 'mic', 'smp', 'fullfilename', 'Date_dataset', 'filewithpath', 'ZCR', 'MEANt', 'VARt', 'SKEWt', 'KURTt', 'LEQt', 'BGNt', 'SNRt', 'MED', 'Ht', 'ACTtFraction', 'ACTtCount', 'ACTtMean', 'EVNtFraction', 'EVNtMean', 'EVNtCount', 'MEANf', 'VARf', 'SKEWf', 'KURTf', 'NBPEAKS', 'LEQf', 'ENRf', 'BGNf', 'SNRf', 'Hf', 'EAS', 'ECU', 'ECV', 'EPS', 'EPS_KURT', 'EPS_SKEW', 'ACI', 'NDSI', 'rBA', 'AnthroEnergy', 'BioEnergy', 'BI', 'ROU', 'ADI', 'AEI', 'LFC', 'MFC', 'HFC', 'ACTspFract', 'ACTspCount', 'ACTspMean', 'EVNspFract', 'EVNspMean', 'EVNspCount', 'TFSD', 'H_Havrda', 'H_Renyi', 'H_pairedShannon', 'H_gamma', 'H_GiniSimpson', 'RAOQ', 'AGI', 'ROItotal', 'ROIcover', 'bird_1', 'confidence_1', 'bird_2', 'confidence_2', 'bird_3', 'confidence_3', 'bird_4', 'confidence_4', 'bird_5', 'confidence_5', 'Key', 'Tempo_Estimates', 'Onsets', 'chordhmm', 'chroma', 'chord', 'chordtime', 'file_name', 'frequencies', 'LTS', 'MEANt_per_bin', 'VARt_per_bin', 'SKEWt_per_bin', 'KURTt_per_bin', 'LEQf_per_bin', 'ENRf_per_bin', 'BGNf_per_bin', 'SNRf_per_bin', 'Ht_per_bin', 'ACI_per_bin', 'ROU_per_bin', 'ACTspFract_per_bin', 'ACTspCount_per_bin', 'EVNspFract_per_bin', 'EVNspMean_per_bin', 'EVNspCount_per_bin', 'AGI_per_bin', 'isclipped', 'ismusic', 'isspeech', 'class_1', 'confidence_voice_1', 'class_2', 'confidence_voice_2', 'class_3', 'confidence_voice_3', 'class_4', 'confidence_voice_4', 'class_5', 'confidence_voice_5', 'class_6', 'confidence_voice_6', 'class_7', 'confidence_voice_7', 'class_8', 'confidence_voice_8', 'class_9', 'confidence_voice_9', 'class_10', 'confidence_voice_10', 'process']
# 查询数据
df_sample = query_database(columns, "audioglobal1", engine)
df_sample

,file,realfilename,foldername,birdenname,birdspgen,Date,gen,sp,ssp,group,...,confidence_voice_6,class_7,confidence_voice_7,class_8,confidence_voice_8,class_9,confidence_voice_9,class_10,confidence_voice_10,process
0,XC767544.mp3,XC767544,Cygnus columbianus_Tundra Swan,Tundra Swan,Cygnus columbianus,2022-12-08 04:44:00,Cygnus,columbianus,bewickii,birds,...,None,None,None,None,None,None,None,None,None,origin
1,XC829355.mp3,XC829355,Numenius phaeopus_Eurasian Whimbrel,Eurasian Whimbrel,Numenius phaeopus,2023-09-08 06:36:00,Numenius,phaeopus,variegatus,birds,...,None,None,None,None,None,None,None,None,None,origin
2,XC774250.mp3,XC774250,Anas crecca_Eurasian Teal,Eurasian Teal,Anas crecca,2023-01-02 05:30:00,Anas,crecca,,birds,...,None,None,None,None,None,None,None,None,None,origin
3,XC730489.mp3,XC730489,Fulica atra_Eurasian Coot,Eurasian Coot,Fulica atra,2022-04-30 23:30:00,Fulica,atra,,birds,...,None,None,None,None,None,None,None,None,None,origin
4,XC635298.mp3,XC635298,Gallinula chloropus_Common Moorhen,Common Moorhen,Gallinula chloropus,2021-04-02 15:00:00,Gallinula,chloropus,,birds,...,None,None,None,None,None,None,None,None,None,origin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,XC605756.mp3,XC605756,Anas platyrhynchos_Mallard,Mallard,Anas platyrhynchos,2020-11-16 17:00:00,Anas,platyrhynchos,,birds,...,None,None,None,None,None,None,None,None,None,origin
96,XC803083.mp3,XC803083,Anas crecca_Eurasian Teal,Eurasian Teal,Anas crecca,2023-05-20 23:00:00,Anas,crecca,,birds,...,None,None,None,None,None,None,None,None,None,origin
97,XC698774.mp3,XC698774,Anas crecca_Eurasian Teal,Eurasian Teal,Anas crecca,2022-01-01 10:30:00,Anas,crecca,,birds,...,None,None,None,None,None,None,None,None,None,origin
98,XC570753.mp3,XC570753,Gallinula chloropus_Common Moorhen,Common Moorhen,Gallinula chloropus,2020-06-18 10:16:00,Gallinula,chloropus,,birds,...,None,None,None,None,None,None,None,None,None,origin
99,XC554304.mp3,XC554304,Gallinula chloropus_Common Moorhen,Common Moorhen,Gallinula chloropus,2020-05-05 01:25:00,Gallinula,chloropus,,birds,...,None,None,None,None,None,None,None,None,None,origin

In [5]:
def query_database(columns, table_name, engine):
    # 构建 SQL 查询
    column_str = ', '.join([f'"{col}"' for col in columns])
    query = f'SELECT {column_str} FROM {table_name}'
    

    # 执行查询并加载数据到 DataFrame
    try:
        df = pd.read_sql_query(text(query), con=engine)
        return df
    except Exception as e:
        print("Error in query execution:", e)
        return None

In [18]:
# 定义 SQL 查询，确保列名大小写正确
columns = ['Date', 'birdenname', 'birdspgen','file', 'realfilename','rec', 'cnt', 'loc', 'lat', 'lng','also','q','type']
table_name = "audioglobal1"
# 使用 pandas 的 read_sql_query 函数直接加载数据到 DataFrame
df = query_database(columns, table_name, engine)
df.to_pickle('fileinformation.pkl')

In [19]:
# 定义 SQL 查询，确保列名大小写正确
columns = ['Date', 'birdenname', 'birdspgen','file', 'realfilename','rec', 'cnt', 'loc', 'lat', 'lng','also','q','type','ZCR', 'MEANt', 'VARt', 'SKEWt', 'KURTt', 'LEQt', 'BGNt', 'SNRt', 'MED', 'Ht', 'ACTtFraction', 'ACTtCount', 'ACTtMean', 'EVNtFraction', 'EVNtMean', 'EVNtCount', 'MEANf', 'VARf', 'SKEWf', 'KURTf', 'NBPEAKS', 'LEQf', 'ENRf', 'BGNf', 'SNRf', 'Hf', 'EAS', 'ECU', 'ECV', 'EPS', 'EPS_KURT', 'EPS_SKEW', 'ACI', 'NDSI', 'rBA', 'AnthroEnergy', 'BioEnergy', 'BI', 'ROU', 'ADI', 'AEI', 'LFC', 'MFC', 'HFC', 'ACTspFract', 'ACTspCount', 'ACTspMean', 'EVNspFract', 'EVNspMean', 'EVNspCount', 'TFSD', 'H_Havrda', 'H_Renyi', 'H_pairedShannon', 'H_gamma', 'H_GiniSimpson', 'RAOQ', 'AGI', 'ROItotal', 'ROIcover']
table_name = "audioglobal1"
# 使用 pandas 的 read_sql_query 函数直接加载数据到 DataFrame
df = query_database(columns, table_name, engine)

In [20]:
df.to_pickle('soundfeature_other.pkl')

In [6]:
# 定义 SQL 查询，确保列名大小写正确
columns = ['Date', 'birdenname', 'birdspgen','file', 'realfilename','rec', 'cnt', 'loc', 'lat', 'lng','also','q','type', 'chord', 'chordtime','Key']
table_name = "audioglobal1"
# 使用 pandas 的 read_sql_query 函数直接加载数据到 DataFrame
df = query_database(columns, table_name, engine)

In [7]:
df.to_pickle('music_var_chordkey.pkl')

In [23]:
# 定义 SQL 查询，确保列名大小写正确
columns = ['Date', 'birdenname', 'birdspgen','file', 'realfilename','rec', 'cnt', 'loc', 'lat', 'lng','also','q','type','Tempo_Estimates', 'Onsets']
table_name = "audioglobal1"
# 使用 pandas 的 read_sql_query 函数直接加载数据到 DataFrame
df = query_database(columns, table_name, engine)

In [24]:
df.to_pickle('music_var_tempo.pkl')

In [25]:
# 定义 SQL 查询，确保列名大小写正确
columns = ['Date', 'birdenname', 'birdspgen','file', 'realfilename','rec', 'cnt', 'loc', 'lat', 'lng','also','q','type','bird_1', 'confidence_1', 'bird_2', 'confidence_2', 'bird_3', 'confidence_3', 'bird_4', 'confidence_4', 'bird_5', 'confidence_5','class_1', 'confidence_voice_1', 'class_2', 'confidence_voice_2', 'class_3', 'confidence_voice_3', 'class_4', 'confidence_voice_4', 'class_5', 'confidence_voice_5', 'class_6', 'confidence_voice_6', 'class_7', 'confidence_voice_7', 'class_8', 'confidence_voice_8', 'class_9', 'confidence_voice_9', 'class_10', 'confidence_voice_10']
table_name = "audioglobal1"
# 使用 pandas 的 read_sql_query 函数直接加载数据到 DataFrame
df = query_database(columns, table_name, engine)

In [26]:
df.to_pickle('class_var.pkl')

In [27]:
# 定义 SQL 查询，确保列名大小写正确
columns = ['Date', 'birdenname', 'birdspgen','file', 'realfilename','rec', 'cnt', 'loc', 'lat', 'lng','also','q','type','NDSI', 'ADI', 'ACI', 'RAOQ','AnthroEnergy','rBA','BioEnergy','BI','AEI','H_pairedShannon']
table_name = "audioglobal1"
# 使用 pandas 的 read_sql_query 函数直接加载数据到 DataFrame
df = query_database(columns, table_name, engine)

In [28]:
df.to_pickle('basic_var.pkl')

In [29]:

df

,Date,birdenname,birdspgen,file,realfilename,rec,cnt,loc,lat,lng,...,NDSI,ADI,ACI,RAOQ,AnthroEnergy,rBA,BioEnergy,BI,AEI,H_pairedShannon
0,2022-01-16 00:00:00,Eurasian Teal,Anas crecca,XC706499.mp3,XC706499,Irish Wildlife Sounds,Ireland,"Tacumshane, Wexford, County Wexford",52.1853,-6.4000,...,-0.987135,0.856167,302.30112,0.004398,1.609471,0.006474,0.010420,20.516189,0.758432,3.116815
1,2023-12-13 10:03:00,Eurasian Teal,Anas crecca,XC872164.mp3,XC872164,Johannes Dag Mayer,Germany,"Suedsee, Laupheim, Biberach, Tübingen, Baden-W...",48.2078,9.8415,...,0.041202,2.078385,300.95508,0.677393,0.007155,1.085946,0.007770,7.909118,0.025495,5.120108
2,2024-11-04 08:11:00,Eurasian Teal,Anas crecca,XC946313.mp3,XC946313,Sonothèque ADVL,France,"Cabane Vauban (Carolles), Manche, Normandie",48.7443,-1.5693,...,-0.905694,2.025688,312.27832,0.054279,0.016836,0.049486,0.000833,16.520046,0.182821,4.060774
3,2014-07-13 09:00:00,Eurasian Teal,Anas crecca,XC187090.mp3,XC187090,Albert Lastukhin,Russian Federation,"Novocheboksarsk, gorod Novocheboksarsk, Chuvas...",56.1056,47.5392,...,-0.089313,2.044824,313.51868,0.325825,0.119378,0.836020,0.099802,13.025964,0.144485,5.796961
4,2023-12-18 15:03:00,Eurasian Teal,Anas crecca,XC872174.mp3,XC872174,Johannes Dag Mayer,Germany,"Suedsee, Laupheim, Biberach, Tübingen, Baden-W...",48.2078,9.8415,...,-0.167407,2.067609,300.16153,0.703713,0.018217,0.713198,0.012992,8.142680,0.084404,5.676070
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14620,2020-10-04 21:05:00,Greater White-fronted Goose,Anser albifrons,XC592979.mp3,XC592979,Juha Saari,Finland,"Pihlajamäki, Helsinki, Uusimaa",60.2357,25.0058,...,-0.233935,1.400769,330.75983,0.112048,14.061728,0.620831,8.729958,43.422633,0.610619,4.989973
14621,2022-10-02 22:00:00,Greater White-fronted Goose,Anser albifrons,XC753535.mp3,XC753535,Uku Paal,Estonia,"Tartu, Tartu City, Tartu maakond",58.3752,26.6899,...,-0.381174,2.033413,298.47372,0.127290,1.978635,0.448043,0.886514,12.645537,0.168072,4.855840
14622,2008-02-17 19:05:00,Greater White-fronted Goose,Anser albifrons,XC280889.mp3,XC280889,Peter Boesman,Belgium,"Uitkerkse polders, West-Vlaanderen",51.2950,3.1150,...,-0.205119,1.279218,352.08865,0.016740,5.135168,0.659587,3.387090,79.866655,0.654794,3.902131
14623,2021-11-23 01:36:00,Greater White-fronted Goose,Anser albifrons,XC718649.mp3,XC718649,Chèvremont Fabian,Belgium,"Fléron, Liège, Wallonie",50.6041,5.6641,...,-0.669254,2.079096,317.26410,0.279683,0.088989,0.198140,0.017632,10.011921,0.014913,4.937674
14624,2020-11-04 01:39:00,Greater White-fronted Goose,Anser albifrons,XC606962.mp3,XC606962,Mark Pearson,United Kingdom,"Filey, North Yorkshire, England",54.2081,-0.2889,...,-0.919362,2.055657,294.09576,0.040628,0.055838,0.042013,0.002346,13.620456,0.122365,3.963617

In [34]:
pd.read_pickle("basic_var.pkl").to_csv("basic_var.csv")
pd.read_pickle("class_var.pkl").to_csv("class_var.csv")
pd.read_pickle("music_var_tempo.pkl").to_csv("music_var_tempo.csv")
pd.read_pickle("soundfeature_other.pkl").to_csv("soundfeature_other.csv")
pd.read_pickle("music_var_chordkey.pkl").to_csv("music_var_chordkey.csv")